# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PKUDiary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PKUDiary
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  
  target 'PKUDiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
